project_name: mmaudio-semantic-alignment
run_name: initial-run
checkpoint_dir: checkpoints/

# Model configuration
model:
  video_dim: 1024
  audio_dim: 768
  hidden_dim: 1024
  num_heads: 8
  depth: 6
  max_video_frames: 32
  max_audio_frames: 1024
  video_model: r3d_18

# Feature extraction configuration
features:
  video_model: r3d_18
  audio_model: facebook/wav2vec2-base
  frame_rate: 30
  sample_rate: 16000
  hop_length: 160

# Training configuration
training:
  batch_size: 32
  learning_rate: 1e-4
  min_lr: 1e-6
  weight_decay: 0.01
  max_epochs: 100
  grad_clip_val: 1.0
  use_amp: true
  num_workers: 4

# Loss weights
loss:
  recon_weight: 1.0
  contrast_weight: 0.5
  align_weight: 0.1

# Data configuration
data:
  train_video_dir: data/train/videos
  train_audio_dir: data/train/audio
  val_video_dir: data/val/videos
  val_audio_dir: data/val/audio
  test_video_dir: data/test/videos
  test_audio_dir: data/test/audio 